'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace SSTS_WebService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Service1Soap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Service1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private getPendingJobsCountOperationCompleted As System.Threading.SendOrPostCallback
        
        Private updateJobStateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getPendingJobsInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getDeviceStatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportConfigurationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportTransactionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportStatus_SWOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportStatus_HwOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportStatus_Hw_ExtOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportKeepAliveOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportUpdateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportAlertOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetTerminalActiveCommandTypeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetDeviceConfigurationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportCommandCompletedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportPerformanceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReportCountersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.mvCloudAPI.My.MySettings.Default.sstCloudAPI_SSTS_WebService_Service1
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getPendingJobsCountCompleted As getPendingJobsCountCompletedEventHandler
        
        '''<remarks/>
        Public Event updateJobStateCompleted As updateJobStateCompletedEventHandler
        
        '''<remarks/>
        Public Event getPendingJobsInfoCompleted As getPendingJobsInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event getDeviceStatusCompleted As getDeviceStatusCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportConfigurationCompleted As ReportConfigurationCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportTransactionCompleted As ReportTransactionCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportStatus_SWCompleted As ReportStatus_SWCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportStatus_HwCompleted As ReportStatus_HwCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportStatus_Hw_ExtCompleted As ReportStatus_Hw_ExtCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportKeepAliveCompleted As ReportKeepAliveCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportUpdateCompleted As ReportUpdateCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportAlertCompleted As ReportAlertCompletedEventHandler
        
        '''<remarks/>
        Public Event GetTerminalActiveCommandTypeCompleted As GetTerminalActiveCommandTypeCompletedEventHandler
        
        '''<remarks/>
        Public Event GetDeviceConfigurationCompleted As GetDeviceConfigurationCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportCommandCompletedCompleted As ReportCommandCompletedCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportPerformanceCompleted As ReportPerformanceCompletedEventHandler
        
        '''<remarks/>
        Public Event ReportCountersCompleted As ReportCountersCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPendingJobsCount", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getPendingJobsCount(ByVal customerID As String, ByVal deviceId As String) As Integer
            Dim results() As Object = Me.Invoke("getPendingJobsCount", New Object() {customerID, deviceId})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getPendingJobsCountAsync(ByVal customerID As String, ByVal deviceId As String)
            Me.getPendingJobsCountAsync(customerID, deviceId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getPendingJobsCountAsync(ByVal customerID As String, ByVal deviceId As String, ByVal userState As Object)
            If (Me.getPendingJobsCountOperationCompleted Is Nothing) Then
                Me.getPendingJobsCountOperationCompleted = AddressOf Me.OngetPendingJobsCountOperationCompleted
            End If
            Me.InvokeAsync("getPendingJobsCount", New Object() {customerID, deviceId}, Me.getPendingJobsCountOperationCompleted, userState)
        End Sub
        
        Private Sub OngetPendingJobsCountOperationCompleted(ByVal arg As Object)
            If (Not (Me.getPendingJobsCountCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getPendingJobsCountCompleted(Me, New getPendingJobsCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/updateJobState", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function updateJobState(ByVal customerID As String, ByVal idJob As String, ByVal idJobState As String, ByVal idDevice As String) As Boolean
            Dim results() As Object = Me.Invoke("updateJobState", New Object() {customerID, idJob, idJobState, idDevice})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub updateJobStateAsync(ByVal customerID As String, ByVal idJob As String, ByVal idJobState As String, ByVal idDevice As String)
            Me.updateJobStateAsync(customerID, idJob, idJobState, idDevice, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub updateJobStateAsync(ByVal customerID As String, ByVal idJob As String, ByVal idJobState As String, ByVal idDevice As String, ByVal userState As Object)
            If (Me.updateJobStateOperationCompleted Is Nothing) Then
                Me.updateJobStateOperationCompleted = AddressOf Me.OnupdateJobStateOperationCompleted
            End If
            Me.InvokeAsync("updateJobState", New Object() {customerID, idJob, idJobState, idDevice}, Me.updateJobStateOperationCompleted, userState)
        End Sub
        
        Private Sub OnupdateJobStateOperationCompleted(ByVal arg As Object)
            If (Not (Me.updateJobStateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent updateJobStateCompleted(Me, New updateJobStateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPendingJobsInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getPendingJobsInfo(ByVal customerID As String, ByVal deviceId As String) As P_Jobs
            Dim results() As Object = Me.Invoke("getPendingJobsInfo", New Object() {customerID, deviceId})
            Return CType(results(0),P_Jobs)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getPendingJobsInfoAsync(ByVal customerID As String, ByVal deviceId As String)
            Me.getPendingJobsInfoAsync(customerID, deviceId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getPendingJobsInfoAsync(ByVal customerID As String, ByVal deviceId As String, ByVal userState As Object)
            If (Me.getPendingJobsInfoOperationCompleted Is Nothing) Then
                Me.getPendingJobsInfoOperationCompleted = AddressOf Me.OngetPendingJobsInfoOperationCompleted
            End If
            Me.InvokeAsync("getPendingJobsInfo", New Object() {customerID, deviceId}, Me.getPendingJobsInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OngetPendingJobsInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.getPendingJobsInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getPendingJobsInfoCompleted(Me, New getPendingJobsInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getDeviceStatus", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getDeviceStatus(ByVal customerID As String, ByVal deviceId As String) As Integer
            Dim results() As Object = Me.Invoke("getDeviceStatus", New Object() {customerID, deviceId})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getDeviceStatusAsync(ByVal customerID As String, ByVal deviceId As String)
            Me.getDeviceStatusAsync(customerID, deviceId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getDeviceStatusAsync(ByVal customerID As String, ByVal deviceId As String, ByVal userState As Object)
            If (Me.getDeviceStatusOperationCompleted Is Nothing) Then
                Me.getDeviceStatusOperationCompleted = AddressOf Me.OngetDeviceStatusOperationCompleted
            End If
            Me.InvokeAsync("getDeviceStatus", New Object() {customerID, deviceId}, Me.getDeviceStatusOperationCompleted, userState)
        End Sub
        
        Private Sub OngetDeviceStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.getDeviceStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getDeviceStatusCompleted(Me, New getDeviceStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportConfiguration", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportConfiguration(ByVal o As P_C, ByVal customerID As String) As Integer
            Dim results() As Object = Me.Invoke("ReportConfiguration", New Object() {o, customerID})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportConfigurationAsync(ByVal o As P_C, ByVal customerID As String)
            Me.ReportConfigurationAsync(o, customerID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportConfigurationAsync(ByVal o As P_C, ByVal customerID As String, ByVal userState As Object)
            If (Me.ReportConfigurationOperationCompleted Is Nothing) Then
                Me.ReportConfigurationOperationCompleted = AddressOf Me.OnReportConfigurationOperationCompleted
            End If
            Me.InvokeAsync("ReportConfiguration", New Object() {o, customerID}, Me.ReportConfigurationOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportConfigurationOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportConfigurationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportConfigurationCompleted(Me, New ReportConfigurationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportTransaction", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportTransaction(ByVal aP_T() As P_T, ByVal customerID As String) As R()
            Dim results() As Object = Me.Invoke("ReportTransaction", New Object() {aP_T, customerID})
            Return CType(results(0),R())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportTransactionAsync(ByVal aP_T() As P_T, ByVal customerID As String)
            Me.ReportTransactionAsync(aP_T, customerID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportTransactionAsync(ByVal aP_T() As P_T, ByVal customerID As String, ByVal userState As Object)
            If (Me.ReportTransactionOperationCompleted Is Nothing) Then
                Me.ReportTransactionOperationCompleted = AddressOf Me.OnReportTransactionOperationCompleted
            End If
            Me.InvokeAsync("ReportTransaction", New Object() {aP_T, customerID}, Me.ReportTransactionOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportTransactionOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportTransactionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportTransactionCompleted(Me, New ReportTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportStatus_SW", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportStatus_SW(ByVal oPEst As P_S, ByVal customerID As String) As Integer
            Dim results() As Object = Me.Invoke("ReportStatus_SW", New Object() {oPEst, customerID})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportStatus_SWAsync(ByVal oPEst As P_S, ByVal customerID As String)
            Me.ReportStatus_SWAsync(oPEst, customerID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportStatus_SWAsync(ByVal oPEst As P_S, ByVal customerID As String, ByVal userState As Object)
            If (Me.ReportStatus_SWOperationCompleted Is Nothing) Then
                Me.ReportStatus_SWOperationCompleted = AddressOf Me.OnReportStatus_SWOperationCompleted
            End If
            Me.InvokeAsync("ReportStatus_SW", New Object() {oPEst, customerID}, Me.ReportStatus_SWOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportStatus_SWOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportStatus_SWCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportStatus_SWCompleted(Me, New ReportStatus_SWCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportStatus_Hw", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportStatus_Hw(ByVal aO() As P_Hw, ByVal customerID As String) As R()
            Dim results() As Object = Me.Invoke("ReportStatus_Hw", New Object() {aO, customerID})
            Return CType(results(0),R())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportStatus_HwAsync(ByVal aO() As P_Hw, ByVal customerID As String)
            Me.ReportStatus_HwAsync(aO, customerID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportStatus_HwAsync(ByVal aO() As P_Hw, ByVal customerID As String, ByVal userState As Object)
            If (Me.ReportStatus_HwOperationCompleted Is Nothing) Then
                Me.ReportStatus_HwOperationCompleted = AddressOf Me.OnReportStatus_HwOperationCompleted
            End If
            Me.InvokeAsync("ReportStatus_Hw", New Object() {aO, customerID}, Me.ReportStatus_HwOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportStatus_HwOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportStatus_HwCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportStatus_HwCompleted(Me, New ReportStatus_HwCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportStatus_Hw_Ext", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportStatus_Hw_Ext(ByVal aO() As P_Hw_Ext, ByVal customerID As String) As R()
            Dim results() As Object = Me.Invoke("ReportStatus_Hw_Ext", New Object() {aO, customerID})
            Return CType(results(0),R())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportStatus_Hw_ExtAsync(ByVal aO() As P_Hw_Ext, ByVal customerID As String)
            Me.ReportStatus_Hw_ExtAsync(aO, customerID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportStatus_Hw_ExtAsync(ByVal aO() As P_Hw_Ext, ByVal customerID As String, ByVal userState As Object)
            If (Me.ReportStatus_Hw_ExtOperationCompleted Is Nothing) Then
                Me.ReportStatus_Hw_ExtOperationCompleted = AddressOf Me.OnReportStatus_Hw_ExtOperationCompleted
            End If
            Me.InvokeAsync("ReportStatus_Hw_Ext", New Object() {aO, customerID}, Me.ReportStatus_Hw_ExtOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportStatus_Hw_ExtOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportStatus_Hw_ExtCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportStatus_Hw_ExtCompleted(Me, New ReportStatus_Hw_ExtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportKeepAlive", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportKeepAlive(ByVal deviceId As String, ByVal customerID As String) As Integer
            Dim results() As Object = Me.Invoke("ReportKeepAlive", New Object() {deviceId, customerID})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportKeepAliveAsync(ByVal deviceId As String, ByVal customerID As String)
            Me.ReportKeepAliveAsync(deviceId, customerID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportKeepAliveAsync(ByVal deviceId As String, ByVal customerID As String, ByVal userState As Object)
            If (Me.ReportKeepAliveOperationCompleted Is Nothing) Then
                Me.ReportKeepAliveOperationCompleted = AddressOf Me.OnReportKeepAliveOperationCompleted
            End If
            Me.InvokeAsync("ReportKeepAlive", New Object() {deviceId, customerID}, Me.ReportKeepAliveOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportKeepAliveOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportKeepAliveCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportKeepAliveCompleted(Me, New ReportKeepAliveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportUpdate", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportUpdate(ByVal oUpd As P_U, ByVal customerID As String) As Integer
            Dim results() As Object = Me.Invoke("ReportUpdate", New Object() {oUpd, customerID})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportUpdateAsync(ByVal oUpd As P_U, ByVal customerID As String)
            Me.ReportUpdateAsync(oUpd, customerID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportUpdateAsync(ByVal oUpd As P_U, ByVal customerID As String, ByVal userState As Object)
            If (Me.ReportUpdateOperationCompleted Is Nothing) Then
                Me.ReportUpdateOperationCompleted = AddressOf Me.OnReportUpdateOperationCompleted
            End If
            Me.InvokeAsync("ReportUpdate", New Object() {oUpd, customerID}, Me.ReportUpdateOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportUpdateOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportUpdateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportUpdateCompleted(Me, New ReportUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportAlert", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportAlert(ByVal aA() As P_A, ByVal customerID As String) As R()
            Dim results() As Object = Me.Invoke("ReportAlert", New Object() {aA, customerID})
            Return CType(results(0),R())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportAlertAsync(ByVal aA() As P_A, ByVal customerID As String)
            Me.ReportAlertAsync(aA, customerID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportAlertAsync(ByVal aA() As P_A, ByVal customerID As String, ByVal userState As Object)
            If (Me.ReportAlertOperationCompleted Is Nothing) Then
                Me.ReportAlertOperationCompleted = AddressOf Me.OnReportAlertOperationCompleted
            End If
            Me.InvokeAsync("ReportAlert", New Object() {aA, customerID}, Me.ReportAlertOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportAlertOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportAlertCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportAlertCompleted(Me, New ReportAlertCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTerminalActiveCommandType", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetTerminalActiveCommandType(ByVal deviceId As String, ByVal customerID As Integer) As Integer
            Dim results() As Object = Me.Invoke("GetTerminalActiveCommandType", New Object() {deviceId, customerID})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetTerminalActiveCommandTypeAsync(ByVal deviceId As String, ByVal customerID As Integer)
            Me.GetTerminalActiveCommandTypeAsync(deviceId, customerID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetTerminalActiveCommandTypeAsync(ByVal deviceId As String, ByVal customerID As Integer, ByVal userState As Object)
            If (Me.GetTerminalActiveCommandTypeOperationCompleted Is Nothing) Then
                Me.GetTerminalActiveCommandTypeOperationCompleted = AddressOf Me.OnGetTerminalActiveCommandTypeOperationCompleted
            End If
            Me.InvokeAsync("GetTerminalActiveCommandType", New Object() {deviceId, customerID}, Me.GetTerminalActiveCommandTypeOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetTerminalActiveCommandTypeOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetTerminalActiveCommandTypeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetTerminalActiveCommandTypeCompleted(Me, New GetTerminalActiveCommandTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDeviceConfiguration", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetDeviceConfiguration(ByVal deviceId As String, ByVal customerID As Integer) As P_C_Resp
            Dim results() As Object = Me.Invoke("GetDeviceConfiguration", New Object() {deviceId, customerID})
            Return CType(results(0),P_C_Resp)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetDeviceConfigurationAsync(ByVal deviceId As String, ByVal customerID As Integer)
            Me.GetDeviceConfigurationAsync(deviceId, customerID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetDeviceConfigurationAsync(ByVal deviceId As String, ByVal customerID As Integer, ByVal userState As Object)
            If (Me.GetDeviceConfigurationOperationCompleted Is Nothing) Then
                Me.GetDeviceConfigurationOperationCompleted = AddressOf Me.OnGetDeviceConfigurationOperationCompleted
            End If
            Me.InvokeAsync("GetDeviceConfiguration", New Object() {deviceId, customerID}, Me.GetDeviceConfigurationOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetDeviceConfigurationOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetDeviceConfigurationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetDeviceConfigurationCompleted(Me, New GetDeviceConfigurationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportCommandCompleted", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportCommandCompleted(ByVal deviceId As String, ByVal idCmmdType As String, ByVal localDT As String, ByVal customerID As String) As Integer
            Dim results() As Object = Me.Invoke("ReportCommandCompleted", New Object() {deviceId, idCmmdType, localDT, customerID})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportCommandCompletedAsync(ByVal deviceId As String, ByVal idCmmdType As String, ByVal localDT As String, ByVal customerID As String)
            Me.ReportCommandCompletedAsync(deviceId, idCmmdType, localDT, customerID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportCommandCompletedAsync(ByVal deviceId As String, ByVal idCmmdType As String, ByVal localDT As String, ByVal customerID As String, ByVal userState As Object)
            If (Me.ReportCommandCompletedOperationCompleted Is Nothing) Then
                Me.ReportCommandCompletedOperationCompleted = AddressOf Me.OnReportCommandCompletedOperationCompleted
            End If
            Me.InvokeAsync("ReportCommandCompleted", New Object() {deviceId, idCmmdType, localDT, customerID}, Me.ReportCommandCompletedOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportCommandCompletedOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportCommandCompletedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportCommandCompletedCompleted(Me, New ReportCommandCompletedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportPerformance", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportPerformance(ByVal o As P_P, ByVal customerID As String) As Integer
            Dim results() As Object = Me.Invoke("ReportPerformance", New Object() {o, customerID})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportPerformanceAsync(ByVal o As P_P, ByVal customerID As String)
            Me.ReportPerformanceAsync(o, customerID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportPerformanceAsync(ByVal o As P_P, ByVal customerID As String, ByVal userState As Object)
            If (Me.ReportPerformanceOperationCompleted Is Nothing) Then
                Me.ReportPerformanceOperationCompleted = AddressOf Me.OnReportPerformanceOperationCompleted
            End If
            Me.InvokeAsync("ReportPerformance", New Object() {o, customerID}, Me.ReportPerformanceOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportPerformanceOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportPerformanceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportPerformanceCompleted(Me, New ReportPerformanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReportCounters", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReportCounters(ByVal aP_T() As P_T, ByVal customerID As String) As R()
            Dim results() As Object = Me.Invoke("ReportCounters", New Object() {aP_T, customerID})
            Return CType(results(0),R())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReportCountersAsync(ByVal aP_T() As P_T, ByVal customerID As String)
            Me.ReportCountersAsync(aP_T, customerID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReportCountersAsync(ByVal aP_T() As P_T, ByVal customerID As String, ByVal userState As Object)
            If (Me.ReportCountersOperationCompleted Is Nothing) Then
                Me.ReportCountersOperationCompleted = AddressOf Me.OnReportCountersOperationCompleted
            End If
            Me.InvokeAsync("ReportCounters", New Object() {aP_T, customerID}, Me.ReportCountersOperationCompleted, userState)
        End Sub
        
        Private Sub OnReportCountersOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReportCountersCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReportCountersCompleted(Me, New ReportCountersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class P_Jobs
        
        Private lJobsField() As P_Job
        
        Private iRespField As Integer
        
        '''<remarks/>
        Public Property lJobs() As P_Job()
            Get
                Return Me.lJobsField
            End Get
            Set
                Me.lJobsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property iResp() As Integer
            Get
                Return Me.iRespField
            End Get
            Set
                Me.iRespField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class P_Job
        
        Private bCan_Replace_FilesField As Boolean
        
        Private client_Destination_PathField As String
        
        Private jobNameField As String
        
        Private jobTypeField As String
        
        Private marketing_DSField As Date
        
        Private marketing_DEField As Date
        
        Private marketing_nombreField As String
        
        Private listFilesField() As String
        
        '''<remarks/>
        Public Property bCan_Replace_Files() As Boolean
            Get
                Return Me.bCan_Replace_FilesField
            End Get
            Set
                Me.bCan_Replace_FilesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Client_Destination_Path() As String
            Get
                Return Me.client_Destination_PathField
            End Get
            Set
                Me.client_Destination_PathField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property jobName() As String
            Get
                Return Me.jobNameField
            End Get
            Set
                Me.jobNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property jobType() As String
            Get
                Return Me.jobTypeField
            End Get
            Set
                Me.jobTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property marketing_DS() As Date
            Get
                Return Me.marketing_DSField
            End Get
            Set
                Me.marketing_DSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property marketing_DE() As Date
            Get
                Return Me.marketing_DEField
            End Get
            Set
                Me.marketing_DEField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property marketing_nombre() As String
            Get
                Return Me.marketing_nombreField
            End Get
            Set
                Me.marketing_nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property listFiles() As String()
            Get
                Return Me.listFilesField
            End Get
            Set
                Me.listFilesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class P_P
        
        Private diField As String
        
        Private rauField As String
        
        Private pauField As String
        
        Private ldtField As String
        
        '''<remarks/>
        Public Property di() As String
            Get
                Return Me.diField
            End Get
            Set
                Me.diField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rau() As String
            Get
                Return Me.rauField
            End Get
            Set
                Me.rauField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property pau() As String
            Get
                Return Me.pauField
            End Get
            Set
                Me.pauField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ldt() As String
            Get
                Return Me.ldtField
            End Get
            Set
                Me.ldtField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class P_A
        
        Private diField As String
        
        Private idTField As String
        
        Private ldtField As String
        
        Private dField As String
        
        Private fnField As String
        
        '''<remarks/>
        Public Property di() As String
            Get
                Return Me.diField
            End Get
            Set
                Me.diField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property idT() As String
            Get
                Return Me.idTField
            End Get
            Set
                Me.idTField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ldt() As String
            Get
                Return Me.ldtField
            End Get
            Set
                Me.ldtField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property d() As String
            Get
                Return Me.dField
            End Get
            Set
                Me.dField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fn() As String
            Get
                Return Me.fnField
            End Get
            Set
                Me.fnField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class P_U
        
        Private diField As String
        
        Private rField As String
        
        Private vField As String
        
        Private ldtField As String
        
        '''<remarks/>
        Public Property di() As String
            Get
                Return Me.diField
            End Get
            Set
                Me.diField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property r() As String
            Get
                Return Me.rField
            End Get
            Set
                Me.rField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property v() As String
            Get
                Return Me.vField
            End Get
            Set
                Me.vField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ldt() As String
            Get
                Return Me.ldtField
            End Get
            Set
                Me.ldtField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class P_Hw_Ext
        
        Private diField As String
        
        Private idHDField As String
        
        Private ecField As String
        
        Private ecdField As String
        
        Private ldt_sField As String
        
        Private dField As String
        
        Private ipField As String
        
        '''<remarks/>
        Public Property di() As String
            Get
                Return Me.diField
            End Get
            Set
                Me.diField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property idHD() As String
            Get
                Return Me.idHDField
            End Get
            Set
                Me.idHDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ec() As String
            Get
                Return Me.ecField
            End Get
            Set
                Me.ecField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ecd() As String
            Get
                Return Me.ecdField
            End Get
            Set
                Me.ecdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ldt_s() As String
            Get
                Return Me.ldt_sField
            End Get
            Set
                Me.ldt_sField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property d() As String
            Get
                Return Me.dField
            End Get
            Set
                Me.dField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ip() As String
            Get
                Return Me.ipField
            End Get
            Set
                Me.ipField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class P_Hw
        
        Private diField As String
        
        Private idHDField As String
        
        Private ecField As String
        
        Private ecdField As String
        
        Private ldt_sField As String
        
        Private dField As String
        
        Private fnField As String
        
        '''<remarks/>
        Public Property di() As String
            Get
                Return Me.diField
            End Get
            Set
                Me.diField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property idHD() As String
            Get
                Return Me.idHDField
            End Get
            Set
                Me.idHDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ec() As String
            Get
                Return Me.ecField
            End Get
            Set
                Me.ecField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ecd() As String
            Get
                Return Me.ecdField
            End Get
            Set
                Me.ecdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ldt_s() As String
            Get
                Return Me.ldt_sField
            End Get
            Set
                Me.ldt_sField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property d() As String
            Get
                Return Me.dField
            End Get
            Set
                Me.dField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fn() As String
            Get
                Return Me.fnField
            End Get
            Set
                Me.fnField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class P_S
        
        Private diField As String
        
        Private idStField As String
        
        Private ldtField As String
        
        Private dField As String
        
        '''<remarks/>
        Public Property di() As String
            Get
                Return Me.diField
            End Get
            Set
                Me.diField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property idSt() As String
            Get
                Return Me.idStField
            End Get
            Set
                Me.idStField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ldt() As String
            Get
                Return Me.ldtField
            End Get
            Set
                Me.ldtField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property d() As String
            Get
                Return Me.dField
            End Get
            Set
                Me.dField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class R
        
        Private iCodeField As Integer
        
        Private textField As String
        
        Private fnField As String
        
        '''<remarks/>
        Public Property iCode() As Integer
            Get
                Return Me.iCodeField
            End Get
            Set
                Me.iCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property text() As String
            Get
                Return Me.textField
            End Get
            Set
                Me.textField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fn() As String
            Get
                Return Me.fnField
            End Get
            Set
                Me.fnField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class P_T
        
        Private diField As String
        
        Private imField As String
        
        Private idTField As String
        
        Private idSField As String
        
        Private ldt_sField As String
        
        Private ldt_eField As String
        
        Private fnField As String
        
        Private aField() As String
        
        Private adField() As String
        
        '''<remarks/>
        Public Property di() As String
            Get
                Return Me.diField
            End Get
            Set
                Me.diField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property im() As String
            Get
                Return Me.imField
            End Get
            Set
                Me.imField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property idT() As String
            Get
                Return Me.idTField
            End Get
            Set
                Me.idTField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property idS() As String
            Get
                Return Me.idSField
            End Get
            Set
                Me.idSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ldt_s() As String
            Get
                Return Me.ldt_sField
            End Get
            Set
                Me.ldt_sField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ldt_e() As String
            Get
                Return Me.ldt_eField
            End Get
            Set
                Me.ldt_eField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fn() As String
            Get
                Return Me.fnField
            End Get
            Set
                Me.fnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property a() As String()
            Get
                Return Me.aField
            End Get
            Set
                Me.aField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property aD() As String()
            Get
                Return Me.adField
            End Get
            Set
                Me.adField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HD_I
        
        Private fsField As String
        
        Private tsField As String
        
        Private vnField As String
        
        '''<remarks/>
        Public Property fs() As String
            Get
                Return Me.fsField
            End Get
            Set
                Me.fsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ts() As String
            Get
                Return Me.tsField
            End Get
            Set
                Me.tsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property vn() As String
            Get
                Return Me.vnField
            End Get
            Set
                Me.vnField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Info_Windows
        
        Private hDIField() As HD_I
        
        Private oSnField As String
        
        Private tmField As String
        
        Private lField As String
        
        Private wnField As String
        
        Private rField As String
        
        Private pField As String
        
        '''<remarks/>
        Public Property HDI() As HD_I()
            Get
                Return Me.hDIField
            End Get
            Set
                Me.hDIField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OSn() As String
            Get
                Return Me.oSnField
            End Get
            Set
                Me.oSnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tm() As String
            Get
                Return Me.tmField
            End Get
            Set
                Me.tmField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property l() As String
            Get
                Return Me.lField
            End Get
            Set
                Me.lField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property wn() As String
            Get
                Return Me.wnField
            End Get
            Set
                Me.wnField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property r() As String
            Get
                Return Me.rField
            End Get
            Set
                Me.rField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property p() As String
            Get
                Return Me.pField
            End Get
            Set
                Me.pField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(P_C_Resp)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class P_C
        
        Private diField As String
        
        Private macField As String
        
        Private ipField As String
        
        Private liField As String
        
        Private l_dtField As String
        
        Private vappField As String
        
        Private ivField As String
        
        Private aField() As String
        
        Private addsField As String
        
        Private nField As String
        
        Private mField As String
        
        Private bField As String
        
        Private tzField As String
        
        Private oWIField As Info_Windows
        
        '''<remarks/>
        Public Property di() As String
            Get
                Return Me.diField
            End Get
            Set
                Me.diField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mac() As String
            Get
                Return Me.macField
            End Get
            Set
                Me.macField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ip() As String
            Get
                Return Me.ipField
            End Get
            Set
                Me.ipField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property li() As String
            Get
                Return Me.liField
            End Get
            Set
                Me.liField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property L_dt() As String
            Get
                Return Me.l_dtField
            End Get
            Set
                Me.l_dtField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property vapp() As String
            Get
                Return Me.vappField
            End Get
            Set
                Me.vappField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property iv() As String
            Get
                Return Me.ivField
            End Get
            Set
                Me.ivField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property a() As String()
            Get
                Return Me.aField
            End Get
            Set
                Me.aField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property adds() As String
            Get
                Return Me.addsField
            End Get
            Set
                Me.addsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property n() As String
            Get
                Return Me.nField
            End Get
            Set
                Me.nField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property m() As String
            Get
                Return Me.mField
            End Get
            Set
                Me.mField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property b() As String
            Get
                Return Me.bField
            End Get
            Set
                Me.bField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tz() As String
            Get
                Return Me.tzField
            End Get
            Set
                Me.tzField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property oWI() As Info_Windows
            Get
                Return Me.oWIField
            End Get
            Set
                Me.oWIField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class P_C_Resp
        Inherits P_C
        
        Private iRespCodeField As Integer
        
        '''<remarks/>
        Public Property iRespCode() As Integer
            Get
                Return Me.iRespCodeField
            End Get
            Set
                Me.iRespCodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub getPendingJobsCountCompletedEventHandler(ByVal sender As Object, ByVal e As getPendingJobsCountCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getPendingJobsCountCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub updateJobStateCompletedEventHandler(ByVal sender As Object, ByVal e As updateJobStateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class updateJobStateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub getPendingJobsInfoCompletedEventHandler(ByVal sender As Object, ByVal e As getPendingJobsInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getPendingJobsInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As P_Jobs
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),P_Jobs)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub getDeviceStatusCompletedEventHandler(ByVal sender As Object, ByVal e As getDeviceStatusCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getDeviceStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ReportConfigurationCompletedEventHandler(ByVal sender As Object, ByVal e As ReportConfigurationCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportConfigurationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ReportTransactionCompletedEventHandler(ByVal sender As Object, ByVal e As ReportTransactionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportTransactionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As R()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),R())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ReportStatus_SWCompletedEventHandler(ByVal sender As Object, ByVal e As ReportStatus_SWCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportStatus_SWCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ReportStatus_HwCompletedEventHandler(ByVal sender As Object, ByVal e As ReportStatus_HwCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportStatus_HwCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As R()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),R())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ReportStatus_Hw_ExtCompletedEventHandler(ByVal sender As Object, ByVal e As ReportStatus_Hw_ExtCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportStatus_Hw_ExtCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As R()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),R())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ReportKeepAliveCompletedEventHandler(ByVal sender As Object, ByVal e As ReportKeepAliveCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportKeepAliveCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ReportUpdateCompletedEventHandler(ByVal sender As Object, ByVal e As ReportUpdateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportUpdateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ReportAlertCompletedEventHandler(ByVal sender As Object, ByVal e As ReportAlertCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportAlertCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As R()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),R())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GetTerminalActiveCommandTypeCompletedEventHandler(ByVal sender As Object, ByVal e As GetTerminalActiveCommandTypeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetTerminalActiveCommandTypeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub GetDeviceConfigurationCompletedEventHandler(ByVal sender As Object, ByVal e As GetDeviceConfigurationCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetDeviceConfigurationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As P_C_Resp
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),P_C_Resp)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ReportCommandCompletedCompletedEventHandler(ByVal sender As Object, ByVal e As ReportCommandCompletedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportCommandCompletedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ReportPerformanceCompletedEventHandler(ByVal sender As Object, ByVal e As ReportPerformanceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportPerformanceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ReportCountersCompletedEventHandler(ByVal sender As Object, ByVal e As ReportCountersCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReportCountersCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As R()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),R())
            End Get
        End Property
    End Class
End Namespace
