'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace NEO_Bridge
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="NeoBridgeSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class NeoBridge
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ahorroAbonoCambioPendOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ahorroAbonoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ahorroConsultaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private reversoCambioErrorOperationCompleted As System.Threading.SendOrPostCallback
        
        Private creditoPagoOffOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ahorroAbonoOFFOperationCompleted As System.Threading.SendOrPostCallback
        
        Private creditoConsultaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private creditoPagoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultaSocioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultaCreditosDisponiblesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private revisaOperacionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private validaSocioOperationCompleted As System.Threading.SendOrPostCallback
        
        Private insertTxn_MonitorOperationCompleted As System.Threading.SendOrPostCallback
        
        Private insertTxnRev_MonitorOperationCompleted As System.Threading.SendOrPostCallback
        
        Private insertDotacion_MonitorOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.mvCloudAPI.My.MySettings.Default.sstCloudAPI_NEO_Bridge_NeoBridge
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ahorroAbonoCambioPendCompleted As ahorroAbonoCambioPendCompletedEventHandler
        
        '''<remarks/>
        Public Event ahorroAbonoCompleted As ahorroAbonoCompletedEventHandler
        
        '''<remarks/>
        Public Event ahorroConsultaCompleted As ahorroConsultaCompletedEventHandler
        
        '''<remarks/>
        Public Event reversoCambioErrorCompleted As reversoCambioErrorCompletedEventHandler
        
        '''<remarks/>
        Public Event creditoPagoOffCompleted As creditoPagoOffCompletedEventHandler
        
        '''<remarks/>
        Public Event ahorroAbonoOFFCompleted As ahorroAbonoOFFCompletedEventHandler
        
        '''<remarks/>
        Public Event creditoConsultaCompleted As creditoConsultaCompletedEventHandler
        
        '''<remarks/>
        Public Event creditoPagoCompleted As creditoPagoCompletedEventHandler
        
        '''<remarks/>
        Public Event consultaSocioCompleted As consultaSocioCompletedEventHandler
        
        '''<remarks/>
        Public Event consultaCreditosDisponiblesCompleted As consultaCreditosDisponiblesCompletedEventHandler
        
        '''<remarks/>
        Public Event revisaOperacionCompleted As revisaOperacionCompletedEventHandler
        
        '''<remarks/>
        Public Event validaSocioCompleted As validaSocioCompletedEventHandler
        
        '''<remarks/>
        Public Event insertTxn_MonitorCompleted As insertTxn_MonitorCompletedEventHandler
        
        '''<remarks/>
        Public Event insertTxnRev_MonitorCompleted As insertTxnRev_MonitorCompletedEventHandler
        
        '''<remarks/>
        Public Event insertDotacion_MonitorCompleted As insertDotacion_MonitorCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ahorroAbonoCambioPend", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ahorroAbonoCambioPend() As String
            Dim results() As Object = Me.Invoke("ahorroAbonoCambioPend", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ahorroAbonoCambioPendAsync()
            Me.ahorroAbonoCambioPendAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ahorroAbonoCambioPendAsync(ByVal userState As Object)
            If (Me.ahorroAbonoCambioPendOperationCompleted Is Nothing) Then
                Me.ahorroAbonoCambioPendOperationCompleted = AddressOf Me.OnahorroAbonoCambioPendOperationCompleted
            End If
            Me.InvokeAsync("ahorroAbonoCambioPend", New Object(-1) {}, Me.ahorroAbonoCambioPendOperationCompleted, userState)
        End Sub
        
        Private Sub OnahorroAbonoCambioPendOperationCompleted(ByVal arg As Object)
            If (Not (Me.ahorroAbonoCambioPendCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ahorroAbonoCambioPendCompleted(Me, New ahorroAbonoCambioPendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ahorroAbono", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ahorroAbono(ByVal strURLWS As String, ByVal strNum_Socio As String, ByVal strMonto As String, ByVal strIdUser As String, ByVal strClave As String, ByVal strDispositivo As String, ByVal folioPDA As String, ByVal strCambio As String) As String
            Dim results() As Object = Me.Invoke("ahorroAbono", New Object() {strURLWS, strNum_Socio, strMonto, strIdUser, strClave, strDispositivo, folioPDA, strCambio})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ahorroAbonoAsync(ByVal strURLWS As String, ByVal strNum_Socio As String, ByVal strMonto As String, ByVal strIdUser As String, ByVal strClave As String, ByVal strDispositivo As String, ByVal folioPDA As String, ByVal strCambio As String)
            Me.ahorroAbonoAsync(strURLWS, strNum_Socio, strMonto, strIdUser, strClave, strDispositivo, folioPDA, strCambio, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ahorroAbonoAsync(ByVal strURLWS As String, ByVal strNum_Socio As String, ByVal strMonto As String, ByVal strIdUser As String, ByVal strClave As String, ByVal strDispositivo As String, ByVal folioPDA As String, ByVal strCambio As String, ByVal userState As Object)
            If (Me.ahorroAbonoOperationCompleted Is Nothing) Then
                Me.ahorroAbonoOperationCompleted = AddressOf Me.OnahorroAbonoOperationCompleted
            End If
            Me.InvokeAsync("ahorroAbono", New Object() {strURLWS, strNum_Socio, strMonto, strIdUser, strClave, strDispositivo, folioPDA, strCambio}, Me.ahorroAbonoOperationCompleted, userState)
        End Sub
        
        Private Sub OnahorroAbonoOperationCompleted(ByVal arg As Object)
            If (Not (Me.ahorroAbonoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ahorroAbonoCompleted(Me, New ahorroAbonoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ahorroConsulta", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ahorroConsulta(ByVal strURLWS As String, ByVal strNum_Socio As String, ByVal strIdUser As String, ByVal strDispositivo As String) As String
            Dim results() As Object = Me.Invoke("ahorroConsulta", New Object() {strURLWS, strNum_Socio, strIdUser, strDispositivo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ahorroConsultaAsync(ByVal strURLWS As String, ByVal strNum_Socio As String, ByVal strIdUser As String, ByVal strDispositivo As String)
            Me.ahorroConsultaAsync(strURLWS, strNum_Socio, strIdUser, strDispositivo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ahorroConsultaAsync(ByVal strURLWS As String, ByVal strNum_Socio As String, ByVal strIdUser As String, ByVal strDispositivo As String, ByVal userState As Object)
            If (Me.ahorroConsultaOperationCompleted Is Nothing) Then
                Me.ahorroConsultaOperationCompleted = AddressOf Me.OnahorroConsultaOperationCompleted
            End If
            Me.InvokeAsync("ahorroConsulta", New Object() {strURLWS, strNum_Socio, strIdUser, strDispositivo}, Me.ahorroConsultaOperationCompleted, userState)
        End Sub
        
        Private Sub OnahorroConsultaOperationCompleted(ByVal arg As Object)
            If (Not (Me.ahorroConsultaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ahorroConsultaCompleted(Me, New ahorroConsultaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/reversoCambioError", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function reversoCambioError(ByVal strURLWS As String, ByVal strNumSocio As String, ByVal strCambio As String, ByVal strFolioAut As String, ByVal strDispositivo As String) As String
            Dim results() As Object = Me.Invoke("reversoCambioError", New Object() {strURLWS, strNumSocio, strCambio, strFolioAut, strDispositivo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub reversoCambioErrorAsync(ByVal strURLWS As String, ByVal strNumSocio As String, ByVal strCambio As String, ByVal strFolioAut As String, ByVal strDispositivo As String)
            Me.reversoCambioErrorAsync(strURLWS, strNumSocio, strCambio, strFolioAut, strDispositivo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub reversoCambioErrorAsync(ByVal strURLWS As String, ByVal strNumSocio As String, ByVal strCambio As String, ByVal strFolioAut As String, ByVal strDispositivo As String, ByVal userState As Object)
            If (Me.reversoCambioErrorOperationCompleted Is Nothing) Then
                Me.reversoCambioErrorOperationCompleted = AddressOf Me.OnreversoCambioErrorOperationCompleted
            End If
            Me.InvokeAsync("reversoCambioError", New Object() {strURLWS, strNumSocio, strCambio, strFolioAut, strDispositivo}, Me.reversoCambioErrorOperationCompleted, userState)
        End Sub
        
        Private Sub OnreversoCambioErrorOperationCompleted(ByVal arg As Object)
            If (Not (Me.reversoCambioErrorCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent reversoCambioErrorCompleted(Me, New reversoCambioErrorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/creditoPagoOff", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function creditoPagoOff(ByVal strUrlWs As String, ByVal xml As String) As String
            Dim results() As Object = Me.Invoke("creditoPagoOff", New Object() {strUrlWs, xml})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub creditoPagoOffAsync(ByVal strUrlWs As String, ByVal xml As String)
            Me.creditoPagoOffAsync(strUrlWs, xml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub creditoPagoOffAsync(ByVal strUrlWs As String, ByVal xml As String, ByVal userState As Object)
            If (Me.creditoPagoOffOperationCompleted Is Nothing) Then
                Me.creditoPagoOffOperationCompleted = AddressOf Me.OncreditoPagoOffOperationCompleted
            End If
            Me.InvokeAsync("creditoPagoOff", New Object() {strUrlWs, xml}, Me.creditoPagoOffOperationCompleted, userState)
        End Sub
        
        Private Sub OncreditoPagoOffOperationCompleted(ByVal arg As Object)
            If (Not (Me.creditoPagoOffCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent creditoPagoOffCompleted(Me, New creditoPagoOffCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ahorroAbonoOFF", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ahorroAbonoOFF(ByVal strUrlWs As String, ByVal xml As String) As String
            Dim results() As Object = Me.Invoke("ahorroAbonoOFF", New Object() {strUrlWs, xml})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ahorroAbonoOFFAsync(ByVal strUrlWs As String, ByVal xml As String)
            Me.ahorroAbonoOFFAsync(strUrlWs, xml, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ahorroAbonoOFFAsync(ByVal strUrlWs As String, ByVal xml As String, ByVal userState As Object)
            If (Me.ahorroAbonoOFFOperationCompleted Is Nothing) Then
                Me.ahorroAbonoOFFOperationCompleted = AddressOf Me.OnahorroAbonoOFFOperationCompleted
            End If
            Me.InvokeAsync("ahorroAbonoOFF", New Object() {strUrlWs, xml}, Me.ahorroAbonoOFFOperationCompleted, userState)
        End Sub
        
        Private Sub OnahorroAbonoOFFOperationCompleted(ByVal arg As Object)
            If (Not (Me.ahorroAbonoOFFCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ahorroAbonoOFFCompleted(Me, New ahorroAbonoOFFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/creditoConsulta", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function creditoConsulta(ByVal strURLWS As String, ByVal strNumSocio As String, ByVal strNumPrestamo As String) As String
            Dim results() As Object = Me.Invoke("creditoConsulta", New Object() {strURLWS, strNumSocio, strNumPrestamo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub creditoConsultaAsync(ByVal strURLWS As String, ByVal strNumSocio As String, ByVal strNumPrestamo As String)
            Me.creditoConsultaAsync(strURLWS, strNumSocio, strNumPrestamo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub creditoConsultaAsync(ByVal strURLWS As String, ByVal strNumSocio As String, ByVal strNumPrestamo As String, ByVal userState As Object)
            If (Me.creditoConsultaOperationCompleted Is Nothing) Then
                Me.creditoConsultaOperationCompleted = AddressOf Me.OncreditoConsultaOperationCompleted
            End If
            Me.InvokeAsync("creditoConsulta", New Object() {strURLWS, strNumSocio, strNumPrestamo}, Me.creditoConsultaOperationCompleted, userState)
        End Sub
        
        Private Sub OncreditoConsultaOperationCompleted(ByVal arg As Object)
            If (Not (Me.creditoConsultaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent creditoConsultaCompleted(Me, New creditoConsultaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/creditoPago", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function creditoPago(ByVal strURLWS As String, ByVal strNumSocio As String, ByVal strNumCta As String, ByVal strMonto As String, ByVal strMontoTotal As String, ByVal strCambio As String, ByVal strUserID As String, ByVal strClave As String, ByVal strDispositivo As String, ByVal folioPDA As String) As String
            Dim results() As Object = Me.Invoke("creditoPago", New Object() {strURLWS, strNumSocio, strNumCta, strMonto, strMontoTotal, strCambio, strUserID, strClave, strDispositivo, folioPDA})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub creditoPagoAsync(ByVal strURLWS As String, ByVal strNumSocio As String, ByVal strNumCta As String, ByVal strMonto As String, ByVal strMontoTotal As String, ByVal strCambio As String, ByVal strUserID As String, ByVal strClave As String, ByVal strDispositivo As String, ByVal folioPDA As String)
            Me.creditoPagoAsync(strURLWS, strNumSocio, strNumCta, strMonto, strMontoTotal, strCambio, strUserID, strClave, strDispositivo, folioPDA, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub creditoPagoAsync(ByVal strURLWS As String, ByVal strNumSocio As String, ByVal strNumCta As String, ByVal strMonto As String, ByVal strMontoTotal As String, ByVal strCambio As String, ByVal strUserID As String, ByVal strClave As String, ByVal strDispositivo As String, ByVal folioPDA As String, ByVal userState As Object)
            If (Me.creditoPagoOperationCompleted Is Nothing) Then
                Me.creditoPagoOperationCompleted = AddressOf Me.OncreditoPagoOperationCompleted
            End If
            Me.InvokeAsync("creditoPago", New Object() {strURLWS, strNumSocio, strNumCta, strMonto, strMontoTotal, strCambio, strUserID, strClave, strDispositivo, folioPDA}, Me.creditoPagoOperationCompleted, userState)
        End Sub
        
        Private Sub OncreditoPagoOperationCompleted(ByVal arg As Object)
            If (Not (Me.creditoPagoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent creditoPagoCompleted(Me, New creditoPagoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultaSocio", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function consultaSocio(ByVal strURLWS As String, ByVal strNumTarjeta As String) As String
            Dim results() As Object = Me.Invoke("consultaSocio", New Object() {strURLWS, strNumTarjeta})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultaSocioAsync(ByVal strURLWS As String, ByVal strNumTarjeta As String)
            Me.consultaSocioAsync(strURLWS, strNumTarjeta, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultaSocioAsync(ByVal strURLWS As String, ByVal strNumTarjeta As String, ByVal userState As Object)
            If (Me.consultaSocioOperationCompleted Is Nothing) Then
                Me.consultaSocioOperationCompleted = AddressOf Me.OnconsultaSocioOperationCompleted
            End If
            Me.InvokeAsync("consultaSocio", New Object() {strURLWS, strNumTarjeta}, Me.consultaSocioOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultaSocioOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultaSocioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultaSocioCompleted(Me, New consultaSocioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultaCreditosDisponibles", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function consultaCreditosDisponibles(ByVal strURLWS As String, ByVal strNumSocio As String) As String
            Dim results() As Object = Me.Invoke("consultaCreditosDisponibles", New Object() {strURLWS, strNumSocio})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultaCreditosDisponiblesAsync(ByVal strURLWS As String, ByVal strNumSocio As String)
            Me.consultaCreditosDisponiblesAsync(strURLWS, strNumSocio, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultaCreditosDisponiblesAsync(ByVal strURLWS As String, ByVal strNumSocio As String, ByVal userState As Object)
            If (Me.consultaCreditosDisponiblesOperationCompleted Is Nothing) Then
                Me.consultaCreditosDisponiblesOperationCompleted = AddressOf Me.OnconsultaCreditosDisponiblesOperationCompleted
            End If
            Me.InvokeAsync("consultaCreditosDisponibles", New Object() {strURLWS, strNumSocio}, Me.consultaCreditosDisponiblesOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultaCreditosDisponiblesOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultaCreditosDisponiblesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultaCreditosDisponiblesCompleted(Me, New consultaCreditosDisponiblesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/revisaOperacion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function revisaOperacion(ByVal strURLWS As String, ByVal strNumFolio As String) As String
            Dim results() As Object = Me.Invoke("revisaOperacion", New Object() {strURLWS, strNumFolio})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub revisaOperacionAsync(ByVal strURLWS As String, ByVal strNumFolio As String)
            Me.revisaOperacionAsync(strURLWS, strNumFolio, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub revisaOperacionAsync(ByVal strURLWS As String, ByVal strNumFolio As String, ByVal userState As Object)
            If (Me.revisaOperacionOperationCompleted Is Nothing) Then
                Me.revisaOperacionOperationCompleted = AddressOf Me.OnrevisaOperacionOperationCompleted
            End If
            Me.InvokeAsync("revisaOperacion", New Object() {strURLWS, strNumFolio}, Me.revisaOperacionOperationCompleted, userState)
        End Sub
        
        Private Sub OnrevisaOperacionOperationCompleted(ByVal arg As Object)
            If (Not (Me.revisaOperacionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent revisaOperacionCompleted(Me, New revisaOperacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/validaSocio", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function validaSocio(ByVal strURLWS As String, ByVal strNumSocio As String) As String
            Dim results() As Object = Me.Invoke("validaSocio", New Object() {strURLWS, strNumSocio})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub validaSocioAsync(ByVal strURLWS As String, ByVal strNumSocio As String)
            Me.validaSocioAsync(strURLWS, strNumSocio, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub validaSocioAsync(ByVal strURLWS As String, ByVal strNumSocio As String, ByVal userState As Object)
            If (Me.validaSocioOperationCompleted Is Nothing) Then
                Me.validaSocioOperationCompleted = AddressOf Me.OnvalidaSocioOperationCompleted
            End If
            Me.InvokeAsync("validaSocio", New Object() {strURLWS, strNumSocio}, Me.validaSocioOperationCompleted, userState)
        End Sub
        
        Private Sub OnvalidaSocioOperationCompleted(ByVal arg As Object)
            If (Not (Me.validaSocioCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent validaSocioCompleted(Me, New validaSocioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertTxn_Monitor", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function insertTxn_Monitor(ByVal strURLWS As String, ByVal strIdAtm As String, ByVal strFecha As String, ByVal strHora As String, ByVal strNumTarjeta As String, ByVal strMonto As String, ByVal strTipo As String) As String
            Dim results() As Object = Me.Invoke("insertTxn_Monitor", New Object() {strURLWS, strIdAtm, strFecha, strHora, strNumTarjeta, strMonto, strTipo})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub insertTxn_MonitorAsync(ByVal strURLWS As String, ByVal strIdAtm As String, ByVal strFecha As String, ByVal strHora As String, ByVal strNumTarjeta As String, ByVal strMonto As String, ByVal strTipo As String)
            Me.insertTxn_MonitorAsync(strURLWS, strIdAtm, strFecha, strHora, strNumTarjeta, strMonto, strTipo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub insertTxn_MonitorAsync(ByVal strURLWS As String, ByVal strIdAtm As String, ByVal strFecha As String, ByVal strHora As String, ByVal strNumTarjeta As String, ByVal strMonto As String, ByVal strTipo As String, ByVal userState As Object)
            If (Me.insertTxn_MonitorOperationCompleted Is Nothing) Then
                Me.insertTxn_MonitorOperationCompleted = AddressOf Me.OninsertTxn_MonitorOperationCompleted
            End If
            Me.InvokeAsync("insertTxn_Monitor", New Object() {strURLWS, strIdAtm, strFecha, strHora, strNumTarjeta, strMonto, strTipo}, Me.insertTxn_MonitorOperationCompleted, userState)
        End Sub
        
        Private Sub OninsertTxn_MonitorOperationCompleted(ByVal arg As Object)
            If (Not (Me.insertTxn_MonitorCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent insertTxn_MonitorCompleted(Me, New insertTxn_MonitorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertTxnRev_Monitor", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function insertTxnRev_Monitor(ByVal strURLWS As String, ByVal strIdAtm As String, ByVal strFecha As String, ByVal strHora As String, ByVal strNumTarjeta As String, ByVal strMonto As String) As String
            Dim results() As Object = Me.Invoke("insertTxnRev_Monitor", New Object() {strURLWS, strIdAtm, strFecha, strHora, strNumTarjeta, strMonto})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub insertTxnRev_MonitorAsync(ByVal strURLWS As String, ByVal strIdAtm As String, ByVal strFecha As String, ByVal strHora As String, ByVal strNumTarjeta As String, ByVal strMonto As String)
            Me.insertTxnRev_MonitorAsync(strURLWS, strIdAtm, strFecha, strHora, strNumTarjeta, strMonto, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub insertTxnRev_MonitorAsync(ByVal strURLWS As String, ByVal strIdAtm As String, ByVal strFecha As String, ByVal strHora As String, ByVal strNumTarjeta As String, ByVal strMonto As String, ByVal userState As Object)
            If (Me.insertTxnRev_MonitorOperationCompleted Is Nothing) Then
                Me.insertTxnRev_MonitorOperationCompleted = AddressOf Me.OninsertTxnRev_MonitorOperationCompleted
            End If
            Me.InvokeAsync("insertTxnRev_Monitor", New Object() {strURLWS, strIdAtm, strFecha, strHora, strNumTarjeta, strMonto}, Me.insertTxnRev_MonitorOperationCompleted, userState)
        End Sub
        
        Private Sub OninsertTxnRev_MonitorOperationCompleted(ByVal arg As Object)
            If (Not (Me.insertTxnRev_MonitorCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent insertTxnRev_MonitorCompleted(Me, New insertTxnRev_MonitorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertDotacion_Monitor", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function insertDotacion_Monitor(ByVal strURLWS As String, ByVal strIdAtm As String, ByVal strFecha As String, ByVal strHora As String, ByVal strMontoDot As String) As String
            Dim results() As Object = Me.Invoke("insertDotacion_Monitor", New Object() {strURLWS, strIdAtm, strFecha, strHora, strMontoDot})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub insertDotacion_MonitorAsync(ByVal strURLWS As String, ByVal strIdAtm As String, ByVal strFecha As String, ByVal strHora As String, ByVal strMontoDot As String)
            Me.insertDotacion_MonitorAsync(strURLWS, strIdAtm, strFecha, strHora, strMontoDot, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub insertDotacion_MonitorAsync(ByVal strURLWS As String, ByVal strIdAtm As String, ByVal strFecha As String, ByVal strHora As String, ByVal strMontoDot As String, ByVal userState As Object)
            If (Me.insertDotacion_MonitorOperationCompleted Is Nothing) Then
                Me.insertDotacion_MonitorOperationCompleted = AddressOf Me.OninsertDotacion_MonitorOperationCompleted
            End If
            Me.InvokeAsync("insertDotacion_Monitor", New Object() {strURLWS, strIdAtm, strFecha, strHora, strMontoDot}, Me.insertDotacion_MonitorOperationCompleted, userState)
        End Sub
        
        Private Sub OninsertDotacion_MonitorOperationCompleted(ByVal arg As Object)
            If (Not (Me.insertDotacion_MonitorCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent insertDotacion_MonitorCompleted(Me, New insertDotacion_MonitorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ahorroAbonoCambioPendCompletedEventHandler(ByVal sender As Object, ByVal e As ahorroAbonoCambioPendCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ahorroAbonoCambioPendCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ahorroAbonoCompletedEventHandler(ByVal sender As Object, ByVal e As ahorroAbonoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ahorroAbonoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ahorroConsultaCompletedEventHandler(ByVal sender As Object, ByVal e As ahorroConsultaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ahorroConsultaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub reversoCambioErrorCompletedEventHandler(ByVal sender As Object, ByVal e As reversoCambioErrorCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class reversoCambioErrorCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub creditoPagoOffCompletedEventHandler(ByVal sender As Object, ByVal e As creditoPagoOffCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class creditoPagoOffCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ahorroAbonoOFFCompletedEventHandler(ByVal sender As Object, ByVal e As ahorroAbonoOFFCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ahorroAbonoOFFCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub creditoConsultaCompletedEventHandler(ByVal sender As Object, ByVal e As creditoConsultaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class creditoConsultaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub creditoPagoCompletedEventHandler(ByVal sender As Object, ByVal e As creditoPagoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class creditoPagoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub consultaSocioCompletedEventHandler(ByVal sender As Object, ByVal e As consultaSocioCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultaSocioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub consultaCreditosDisponiblesCompletedEventHandler(ByVal sender As Object, ByVal e As consultaCreditosDisponiblesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultaCreditosDisponiblesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub revisaOperacionCompletedEventHandler(ByVal sender As Object, ByVal e As revisaOperacionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class revisaOperacionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub validaSocioCompletedEventHandler(ByVal sender As Object, ByVal e As validaSocioCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class validaSocioCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub insertTxn_MonitorCompletedEventHandler(ByVal sender As Object, ByVal e As insertTxn_MonitorCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class insertTxn_MonitorCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub insertTxnRev_MonitorCompletedEventHandler(ByVal sender As Object, ByVal e As insertTxnRev_MonitorCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class insertTxnRev_MonitorCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub insertDotacion_MonitorCompletedEventHandler(ByVal sender As Object, ByVal e As insertDotacion_MonitorCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class insertDotacion_MonitorCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
